function data = importfile_vicon_abb_sync(filename, dataLines)
%IMPORTFILE Import data from a text file
%  RECORD20240628114906SQUARESISODIAGONALAB300HZFINAL =
%  IMPORTFILE(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as a table.
%
%  RECORD20240628114906SQUARESISODIAGONALAB300HZFINAL = IMPORTFILE(FILE,
%  DATALINES) reads data for the specified row interval(s) of text file
%  FILENAME. Specify DATALINES as a positive scalar integer or a N-by-2
%  array of positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  record20240628114906squaresisodiagonalAB300Hzfinal = importfile("/Users/felix/00_matlab_repo/Projects/03_Daten/28.06_steuerung_vicon_synchronisiert/record_20240628_114906_squares_isodiagonalA&B_300Hz_final.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 28-Jun-2024 13:53:55

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 40);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["timestamp", "sec", "nanosec", "pv_x", "pv_y", "pv_z", "ov_x", "ov_y", "ov_z", "ov_w", "tcp_speedv_x", "tcp_speedv_y", "tcp_speedv_z", "tcp_speedv", "tcp_angularv_x", "tcp_angularv_y", "tcp_angularv_z", "tcp_angularv", "tcp_accelv__x", "tcp_accelv__y", "tcp_accelv__z", "tcp_accelv", "tcp_accelv_angular_x", "tcp_accelv_angular_y", "tcp_accelv_angular_z", "tcp_accelv_angular", "ps_x", "ps_y", "ps_z", "os_x", "os_y", "os_z", "os_w", "tcp_speeds", "joint_1", "joint_2", "joint_3", "joint_4", "joint_5", "joint_6"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
data = readtable(filename, opts);

end